/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Portfolio_Special.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic'
import * as THREE from 'three';
export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Portfolio_Special.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.glass.geometry} material={materials['Material.012']} position={[-3.565, 6.343, 3.355]} scale={1.039} />
      <mesh geometry={nodes.screen.geometry} material={materials.light} position={[-3.81, 5.085, -1.653]} />
    </group>
  )
}

useGLTF.preload('/Portfolio_Special.glb')

// if (matName.includes("glass")) {
//             newMaterials[key] = new THREE.MeshBasicMaterial({
//                 transmission: 1,
//                 transparent: true,
//                 opacity: 0.3,
//                 color: 0xAEEBFF,
//                 metalness: 0,
//                 roughness: 0.05,
//                 ior: 0.95,
//                 thickness: 0.02,
//                 specularColor: 0xAEEBFF,
//             });