/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Portfolio_Static.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertMaterialsToBasic } from '../utils/convertToBasic'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/Portfolio_Static.glb')
  const newMaterials = convertMaterialsToBasic(materials);

  return (
    <group {...props} dispose={null}>
      
      <mesh geometry={nodes.Six.geometry} material={newMaterials['Texture Set Six']} rotation={[0, -0.723, 0]} scale={117.24} />
      <mesh geometry={nodes.Four.geometry} material={newMaterials['Texture Set Four']} position={[4.048, 8.886, -3.699]} rotation={[-0.329, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.One.geometry} material={newMaterials['Texture Set One']} position={[0, 6.806, -0.082]} />
      <mesh geometry={nodes.Two.geometry} material={newMaterials['Texture Set Two']} position={[-0.494, 2.898, -1.697]} />
      <mesh geometry={nodes.Three.geometry} material={newMaterials['Texture Set Three']} position={[-3.026, 3.502, 3.039]} rotation={[2.178, 1.549, -0.546]} />
      <mesh geometry={nodes.Five.geometry} material={newMaterials['Texture Set Five']} position={[1.2, 3.857, 2.864]} rotation={[-0.079, -0.446, -0.013]} />
    </group>
  )
}

useGLTF.preload('/Portfolio_Static.glb')
